name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fae5e6e05ccb627f790d06f72264430a9a766ee8075c21dd68d3dd5297bc1157"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
