name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5f43d65edcd2e8502d1ec83c67b0dbf0699b500171b53d97784eddd2cf397ab"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
