name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffbd06672e5a9d6db5cb93ea1665f3746190a624f6c24a36efd9cb83896834bd"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
